//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quests.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Point
    {
        public int PointID { get; set; }
        public int QuestID { get; set; }
        public string HintText { get; set; }
        public string Answer { get; set; }
        public string HintImageUrl { get; set; }
        public string TaskImageUrl { get; set; }
        public string TaskText { get; set; }
        public Nullable<bool> HasLocationHint { get; set; }
        public string X { get; set; }
        public string Y { get; set; }
    
        public virtual Quest Quest { get; set; }
    }
}
